## 7. Álgebra linear numérica


**Exemplo 7.1:**

In [78]:
import numpy as np
M = np.array([[1,2,3],[-1,5,0],[7,-2,4]])
v = np.array([3,-1,0])

In [79]:
# solução letra a)
print('a)', v[0] + M[1,2])

# solução letra b)
print('b)',M[2] - 7*M[0])

# solução letra c)
print('c)',np.dot(M,v))

# solução letra d)
print('d)',np.dot(v,[5,-1,4]))
print('  ',np.cross(v,[5,-1,4]))

# solução letra e)
print('e)',np.sqrt(np.sum(v*v)))
#ou np.linalg.norm(v)

a) 3
b) [  0 -16 -17]
c) [ 1 -8 23]
d) 16
   [ -4 -12   2]
e) 3.1622776601683795


Operações entre vetores, entre escalares e vetores, e utilizando funções que não usualmente definidas na álgebra linear, são realizadas elemento a elemento de um `array`. 

In [10]:
# soma de um escalar por vetor
print('2+v = ',2+v)
# cosseno de v
print('np.cos(v)=',np.cos(v))
# exponencial de v
print('np.exp(v)=',np.exp(v))

2+v =  [5 1 2]
np.cos(v)= [-0.9899925   0.54030231  1.        ]
np.exp(v)= [20.08553692  0.36787944  1.        ]


**Exemplo 7.2:**

In [11]:
import numpy as np
A = np.array([[2.1, 5.3, 0.8],
              [1.1,-3.9, 2.2],
              [2.4, 3.5,-0.3]])

b = np.array([15.1, -0.1, 8.5])

x = np.array([1,2,3])

# produto de A por x
print(A.dot(x))

[15.1 -0.1  8.5]


In [12]:
print('det(A)=', np.linalg.det(A))
print('x =', np.linalg.solve(A,b))
print('A⁻¹b =', np.linalg.inv(A).dot(b))

det(A)= 26.588000000000005
x = [1. 2. 3.]
A⁻¹b = [1. 2. 3.]


**Exemplo 7.3:**

In [13]:
x = np.array([-1,0,2,4,10])
# usando um for
norma = 0
for xi in x:
    norma += abs(xi)**2
print ('1)',norma**0.5)

# usando numpy
print('2)',np.sqrt(np.sum(x**2)))

# usando a função pronta
print('3)',np.linalg.norm(x,2))

1) 11.0
2) 11.0
3) 11.0


**Exemplo 7.4:**

In [14]:
A = np.array([[2, 1], 
              [2, 1.001]])
b = np.array([3, 0])

x = np.linalg.solve(A,b)

print (x)

[ 1501.5 -3000. ]


In [15]:
np.linalg.norm(A) * np.linalg.norm(np.linalg.inv(A))

5001.000500000551

In [16]:
 np.linalg.norm(A)

3.162594030222659

In [25]:
 np.linalg.det(A)

0.00199999999999978

In [17]:
A = np.array([[2, 1], [2, 1.002]])
x = np.linalg. solve(A,b)
print (x)

[  751.5 -1500. ]


**Exemplo 7.5:**

In [25]:
A = np.array([[2.,0.,0.], 
              [1.,4.,0.], 
              [1.,1.,1.]]) 
b = [2.,-3.,0.]


def solve_L(L,b): 
    x = np.empty(len(b))
    for i in range(len(b)):
        x[i]=(b[i]-np.sum(L[i,:i]*x[:i]))/L[i,i]
    return (x)


print(solve_L(A,b))

[ 1. -1.  0.]


**Exemplo 7.6:**

In [26]:
A = np.array([[3,1,1], 
              [0,2,-1], 
              [0,0,3]])
b = np.array([4,2,3])


def solve_U(U,b):
    x = np.empty(len(b))
    for i in range(len(b)-1,-1,-1):
        x[i]=(b[i]-np.sum(U[i,i+1:]*x[i+1:]))/U[i,i]
    return (x)

print (solve_U(A,b))

[0.5 1.5 1. ]


**Exemplo 7.7:**

In [36]:
A = np.array([[3,2,4],
              [1,1,2],
              [4,3,2]])
M1 = np.array([[1,             0, 0],
               [-A[1,0]/A[0,0],1, 0],
               [-A[2,0]/A[0,0],0, 1]])

Al = M1.dot(A)
Al

array([[ 3.        ,  2.        ,  4.        ],
       [ 0.        ,  0.33333333,  0.66666667],
       [ 0.        ,  0.33333333, -3.33333333]])

In [38]:
M2 = np.array([[1,0,0],[0,1,0],[0,-Al[2,1]/Al[1,1],1]])
M2

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -1.,  1.]])

In [44]:
#matriz U
= M2.dot(Al)
np.round(U,4)

array([[ 3.    ,  2.    ,  4.    ],
       [ 0.    ,  0.3333,  0.6667],
       [ 0.    ,  0.    , -4.    ]])

In [49]:
# Matriz L
L = np.linalg.inv(M1).dot(np.linalg.inv(M2))
L

array([[1.        , 0.        , 0.        ],
       [0.33333333, 1.        , 0.        ],
       [1.33333333, 1.        , 1.        ]])

In [47]:
L.dot(U)

array([[3., 2., 4.],
       [1., 1., 2.],
       [4., 3., 2.]])

**Exemplo 7.8:**

In [51]:
b = np.array([1,2,3])
y = solve_L(L,b)
y

array([ 1.00000000e+00,  1.66666667e+00, -4.44089210e-16])

In [53]:
x = solve_U(U,y)
x

array([-3.00000000e+00,  5.00000000e+00,  1.11022302e-16])

**Exemplo 7.9:**

In [54]:
import numpy as np

def fatoracao_LU(A):
    n = len(A)     
    U = np.zeros((n,n))
    L = np.identity(n)
    for m in range(n):
        for j in range(m, n):
            U[m,j]=A[m,j]-np.sum(L[m,0:m]*U[0:m,j])
        for i in range(m+1, n):
            L[i,m]=(A[i,m]-np.sum(L[i,0:m]*U[0:m,m]))/U[m,m]
    return L,U

A = np.array([[3,2,4],
              [1,1,2],
              [4,3,2]])
b = [1,2,3]
L,U = fatoracao_LU(A)

print ("Matriz L:")
print (np.array(L))
print ("Matriz U:")
print(np.array(U))

y = solve_L(L,b)
print("y=",np.round(y,4))
x = solve_U(U,y)
print("x=",np.round(x,4))

Matriz L:
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [1.33333333 1.         1.        ]]
Matriz U:
[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.         -4.        ]]
y= [ 1.      1.6667 -0.    ]
x= [-3.  5.  0.]


In [33]:
A = np.array([[2,0,1],[0,2,1],[1,1,3]])
L,U = factor_LU(A)

print ("Matriz L:")
print (L)
print ("Matriz U:")
print(U)

Matriz L:
[[1, 0, 0], [0.0, 1, 0], [0.5, 0.5, 1]]
Matriz U:
[[2, 0, 1], [0, 2.0, 1.0], [0, 0, 2.0]]


**Exemplo 7.10:**

In [58]:
def triangulariza(M):
    for j in range(n-1):
        for i in range(j,n-1):
            m = M[i+1,j]/M[j,j]
            M[i+1] = M[i+1]-m*M[j]
    return (M)

M = np.array([[3.,2.,4.,1.],
              [1.,1.,2.,2.],
              [4.,3.,2.,3.]])
n = len(M)

M = triangulariza(M)
print('Matriz ampliada escalonada:')
print (np.round(M,4))

# separa a matriz ampliada em duas
b = M[0:n+1,n:n+1]       
A = M[0:n+1,0:n] 

# resolve o sistema triangular
(np.round(solve_U(A,b),2))


Matriz ampliada escalonada:
[[ 3.      2.      4.      1.    ]
 [ 0.      0.3333  0.6667  1.6667]
 [ 0.      0.     -4.     -0.    ]]


array([-3.,  5.,  0.])

**Exemplo 7.11:**

In [59]:
def gaussJordan(M):
    n = len(M)
    for k in range(n):
        M[k] = M[k]/M[k,k]
        for i in range(n):
            if i!=k:
                M[i] = M[i] - M[i,k]*M[k]
    return (M)


M = np.array([[3.,2.,4.,1.],
              [1.,1.,2.,2.],
              [4.,3.,2.,3.]])

Mf = gaussJordan(M)
print ('Matriz final:')

print ('Solução:')
print(np.round(Mf,3))

x = Mf[:,-1]

print ('x=',np.round(x,3))

Matriz final:
Solução:
[[ 1.  0.  0. -3.]
 [ 0.  1.  0.  5.]
 [-0. -0.  1.  0.]]
x= [-3.  5.  0.]


**Exemplo 7.11:**

In [60]:
import numpy as np
from numpy.linalg import inv

A = np.array([[3,0,1],[3,2,1],[-3,1,3]])
b = np.array([1,1,3])
x = np.dot(inv(A),b)
print (np.round(x,4))

[-0.  0.  1.]


**Exemplo 7.12:**

In [61]:
def gaussJordan(M):
    n = len(M)
    for k in range(n):
        M[k] = M[k]/M[k,k]
        for i in range(n):
            if i!=k:
                M[i] = M[i] - M[i,k]*M[k]
    return (M)

A = np.array([[2,1,3],[0,-1,1],[1,0,3]], float)
I = np.identity(len(A))
M = np.concatenate((A,I), axis=1)

print ('Matriz ampliada:')
print (M)

print ('Matriz após eliminação:')
Mgj = gaussJordan(M)
print (Mgj )

print ('Matriz inversa:')
Ainv = Mgj[:,3:6]
print(Ainv)

Matriz ampliada:
[[ 2.  1.  3.  1.  0.  0.]
 [ 0. -1.  1.  0.  1.  0.]
 [ 1.  0.  3.  0.  0.  1.]]
Matriz após eliminação:
[[ 1.   0.   0.   1.5  1.5 -2. ]
 [ 0.   1.   0.  -0.5 -1.5  1. ]
 [ 0.   0.   1.  -0.5 -0.5  1. ]]
Matriz inversa:
[[ 1.5  1.5 -2. ]
 [-0.5 -1.5  1. ]
 [-0.5 -0.5  1. ]]


**Exemplo 7.13:**

In [67]:
# Dados iniciais
x = np.array([0.,0.,0.])

# função para fazer as iterações
def itera(x):
    x1 = 2/10 - 5/10*x[1] - 2/10*x[2]
    x2 = 10/5 - 2/5*x[0] - 2/5*x[2]
    x3 = 17/10 - 1/10*x[0] - 4/10*x[1]
    x = np.array([x1, x2, x3])
    return x

#várias iterações e o erro
x_ant = x
for i in range(1,10):
    x = itera(x)
    err = np.max(abs(x-x_ant))/np.max(abs(x))
    x_ant = x
    print (i, np.round(x,4), np.round(err,4))
    
print ("Solução:", np.round(x,4))

1 [0.2 2.  1.7] 1.0
2 [-1.14  1.24  0.88] 1.0806
3 [-0.596  2.104  1.318] 0.4106
4 [-1.1156  1.7112  0.918 ] 0.3036
5 [-0.8392  2.079   1.1271] 0.1769
6 [-1.0649  1.8848  0.9523] 0.1198
7 [-0.9329  2.0451  1.0526] 0.0783
8 [-1.033   1.9521  0.9753] 0.0513
9 [-0.9711  2.0231  1.0225] 0.0351
Solução: [-0.9711  2.0231  1.0225]


In [73]:
A = np.array([[10., 5., 2.],
              [ 2.,5.,2.],
              [ 1.,4.,10.]])
b = np.array([2.,10.,17.])

#Calculando a matriz H
H = A.copy()
g = b.copy()

for i in range(len(A)):
    H[i] = -A[i]/A[i,i]
    g[i] = b[i]/A[i,i]
    
H = H + np.identity(len(A))
print ('H =', H)
print ('g =', g)

# verificando a convergẽncia com a norma inf 
norma_inf = np.sum(abs(H), axis=1).max()
print ('Norma:', norma_inf)

# fazendo as iterações
err = 1
x = np.array([0,0,0])
x_ant = x

print ('Iterações:')
while err>0.01:
    x = np.dot(H,x)+g
    err = abs(max(x-x_ant)/max(x))
    x_ant = x   
    print(np.round(x, 4), ", Err=", np.round(err,5))

H = [[ 0.  -0.5 -0.2]
 [-0.4  0.  -0.4]
 [-0.1 -0.4  0. ]]
g = [0.2 2.  1.7]
Norma: 0.8
Iterações:
[0.2 2.  1.7] , Err= 1.0
[-1.14  1.24  0.88] , Err= 0.6129
[-0.596  2.104  1.318] , Err= 0.41065
[-1.1156  1.7112  0.918 ] , Err= 0.22955
[-0.8392  2.079   1.1271] , Err= 0.17693
[-1.0649  1.8848  0.9523] , Err= 0.09273
[-0.9329  2.0451  1.0526] , Err= 0.07834
[-1.033   1.9521  0.9753] , Err= 0.03959
[-0.9711  2.0231  1.0225] , Err= 0.03508
[-1.016   1.9795  0.9879] , Err= 0.01747
[-0.9873  2.0113  1.0098] , Err= 0.01581
[-1.0076  1.991   0.9942] , Err= 0.00783


**Exemplo 7.14:**

In [76]:
# Dados iniciais
x = np.array([0.,0.,0.])

# função para fazer as iterações
def itera(x):
    x[0] = 2/10 - 5/10*x[1] - 2/10*x[2]
    x[1] = 10/5 - 2/5*x[0] - 2/5*x[2]
    x[2] = 17/10 - 1/10*x[0] - 4/10*x[1]
    return x

#várias iterações e o erro
x_ant = x
for i in range(1,4):
    x = itera(x)
    err = np.max(abs(x-x_ant))/np.max(abs(x))
    x_ant = x.copy()
    print (i,np.round(x,4),",Err=", np.round(err,4))
    
print ("Solução:", np.round(x,4))

1 [0.2   1.92  0.912] ,Err= 0.0
2 [-0.9424  2.0122  0.9894] ,Err= 0.5677
3 [-1.004   2.0058  0.9981] ,Err= 0.0307
Solução: [-1.004   2.0058  0.9981]


**Exemplo 7.15:**

In [77]:
from numpy.linalg import inv

x = np.array([0.,0.,0.])

eps = 0.001
A = np.array([[10., 5., 2.],
              [ 2.,5.,2.],
              [ 1.,4.,10.]])
b = np.array([2.,10.,17.])

n = len(A)
P = np.zeros((n,n))
Q = np.zeros((n,n))
g = np.zeros(n)

for i in range(n):
    P[i,0:i] = -A[i,0:i]/A[i,i]
    Q[i,i+1:n] = -A[i,i+1:n]/A[i,i]
    g[i] = b[i]/A[i,i] 
    
I = np.eye(n)
H = np.dot(inv(I-P),Q)
g = np.dot(inv(I-P),g)

for k in range(3):
    x = np.dot(H,x) + g
    print (np.round(x,4))

[0.2   1.92  0.912]
[-0.9424  2.0122  0.9894]
[-1.004   2.0058  0.9981]
